# Generated by Django 3.2.7 on 2021-09-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('question', 'session')},
        ),
        migrations.AlterIndexTogether(
            name='answers',
            index_together={('question', 'session')},
        ),
    ]
