# Generated by Django 3.1.7 on 2021-09-13 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_answers_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
    ]
