# Generated by Django 3.1.7 on 2021-09-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210913_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='session',
            field=models.CharField(max_length=500),
        ),
    ]
